### PR TITLE
Adds delegate method for monitoring text truncation

### PR DESCRIPTION
**Pull request by spadafiva**

### CODE REVIEW

**Comment by spadafiva** [comment]
@chansen22 I really would love to be able to use this feature for my use case in app. (Hopefully in this week's sprint if I can 😁 ) . Let me know if there's a different method that might work, or if we can find some way to make the truncation status able to be referenced or observed.

**Comment by spadafiva** [comment]
That all makes sense and I actually had a same state check before, so I'll add that bacK in.

The only other thing is that we need a way to get the initial state when the delegate is set if it the truncation status doesn't change.  That's the reason that I went with public with private set.

If you have any other general avenues that you'd like to explore I'm happy to work on them if you give me a rough idea of the direction you're thinking.

**Comment by spadafiva** [comment]
Thanks for making some time to look this over also.

**Comment by chansen22** [comment]
@spadafiva is this something we want to continue with? Let me know how I can help you out here

**Comment by spadafiva** [comment]
Closing this for now

**Pull request closed without merging**
